global:
  scrape_interval: 10s
  evaluation_interval: 10s

# Prometheus scrape config pentru finance-api
scrape_configs:
  - job_name: "finance-api"
    metrics_path: /actuator/prometheus
    scheme: http

    # In docker-compose (finance-api) si in docker-swarm (tasks.finance-api)
    dns_sd_configs:
      - names:
          - "finance-api"
          - "tasks.finance-api"
        type: "A"
        port: 8083
